### ISSUE TITLE
Can i see your other config

### ISSUE THREAD

**Issue by Ghibranalj** [UtkarshVerma/qemu-vfio-win10#1]
Hey. I know im asking a lot. but...
I have the same model laptop as you [(source)](https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF/Examples#UtkarshVerma's_VFIO_Setup).
I even use the same window manager as you  (dwm). pardon me for snooping around your github profile.
It would be really nice to see the content of tour `/etc/default/grub` and `/etc/mkinitcpio.conf`. 
Im having some trouble with this whole thing.

Thank you...

**Comment by UtkarshVerma** [comment]
Hi, I use a [unified kernel image](https://wiki.archlinux.org/title/Unified_kernel_image) instead of grub. You can find my dotfiles for building it in my repo:
https://github.com/UtkarshVerma/dotfiles/tree/main/root/etc
